# Generated by Django 4.2.3 on 2023-10-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_user',
        ),
    ]
